# 图床服务配置文件

[server]
# 服务器监听地址
host = "0.0.0.0"
# 服务器监听端口
port = 3000
# 是否启用CORS
enable_cors = true

[storage]
# 上传文件存储目录
# 注意：文件将按SHA256哈希前2位和第3-4位分层存储在子目录中
# 例如：uploads/a1/b2/a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456.jpg
upload_dir = "uploads"
# 最大文件大小（字节）10MB
max_file_size = 10485760

[logging]
# 日志级别: trace, debug, info, warn, error
level = "info"
# 是否启用日志颜色
enable_color = true

[cache]
# 静态文件缓存时间（秒）1年
max_age = 31536000

[database]
# 数据库类型: sqlite, postgres, mysql
database_type = "sqlite"
# 数据库连接字符串
connection_string = "sqlite:./data/images.db"
# 最大连接数
max_connections = 20 