version: '3.8'

services:
  rifs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/cache
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      # 服务器配置
      RIFS_SERVER_HOST: "0.0.0.0"
      RIFS_SERVER_PORT: 3000
      RIFS_SERVER_ENABLE_CORS: true
      RIFS_SERVER_REQUEST_TIMEOUT: "1m"
      
      # 数据库配置
      RIFS_DATABASE_DATABASE_TYPE: "sqlite"
      RIFS_DATABASE_CONNECTION_STRING: "sqlite:/app/data/images.db"
      RIFS_DATABASE_MAX_CONNECTIONS: 20
      RIFS_DATABASE_MIN_CONNECTIONS: 4
      RIFS_DATABASE_CONNECT_TIMEOUT: "30s"
      RIFS_DATABASE_IDLE_TIMEOUT: "5m"
      RIFS_DATABASE_MAX_LIFETIME: "30m"
      
      # 存储配置
      RIFS_STORAGE_UPLOAD_DIR: "/app/uploads"
      RIFS_STORAGE_MAX_FILE_SIZE: "10MB"
      
      # 缓存配置
      RIFS_CACHE_MAX_AGE: "1y"
      RIFS_CACHE_CACHE_DIR: "/app/cache"
      RIFS_CACHE_ENABLE_TRANSFORM_CACHE: true
      RIFS_CACHE_MAX_CACHE_ENTRIES: 10000
      RIFS_CACHE_MAX_CACHE_SIZE: "100MB"
      RIFS_CACHE_MAX_CACHE_AGE: "30d"
      RIFS_CACHE_AUTO_CLEANUP_INTERVAL: "1h"
      RIFS_CACHE_HEAT_DECAY_FACTOR: 0.98
      RIFS_CACHE_MIN_HEAT_SCORE: 0.1
      RIFS_CACHE_SPACE_THRESHOLD_PERCENT: 0.8
      
      # 日志配置
      RIFS_LOGGING_LEVEL: "info"
      RIFS_LOGGING_ENABLE_COLOR: false
      RIFS_LOGGING_LOG_DIR: "/app/logs"
      RIFS_LOGGING_MAX_LOG_SIZE: "10MB"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
